import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ReactQueryClientProvider } from '@/lib/react-query-client-provider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Footer } from '@/components/footer';
import Header from '@/components/header';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TalkTactics',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={`${inter.className} flex flex-col min-h-screen`}>
          <Header />
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem
            disableTransitionOnChange>
            <div className='flex-grow pt-[70px]'>{children}</div>
          </ThemeProvider>
          <Footer />
          <Toaster />
          {/* <ReactQueryDevtools /> */}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
